### ISSUE TITLE
Issue when trying to build adafruit toolkit

### ISSUE THREAD

**Issue by TheNopePlant** [lukehutch/Adafruit-OLED-Bonnet-Toolkit#1]
Consol output:

[INFO] Scanning for projects...
[INFO] 
[INFO] -----< adafruit-oled-bonnet-toolkit:adafruit-oled-bonnet-toolkit >------
[INFO] Building Adafruit OLED Bonnet Toolkit 0.0.2
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom (8.1 kB at 4.1 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/23/maven-plugins-23.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/23/maven-plugins-23.pom (9.2 kB at 20 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/22/maven-parent-22.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/22/maven-parent-22.pom (30 kB at 59 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/apache/11/apache-11.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/apache/11/apache-11.pom (15 kB at 34 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.jar (30 kB at 66 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.8.1/maven-compiler-plugin-3.8.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.8.1/maven-compiler-plugin-3.8.1.pom (12 kB at 30 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/33/maven-plugins-33.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/33/maven-plugins-33.pom (11 kB at 26 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/33/maven-parent-33.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/33/maven-parent-33.pom (44 kB at 98 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/apache/21/apache-21.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/apache/21/apache-21.pom (17 kB at 42 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.8.1/maven-compiler-plugin-3.8.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.8.1/maven-compiler-plugin-3.8.1.jar (62 kB at 135 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.pom (10 kB at 25 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/2.12.4/surefire-2.12.4.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/2.12.4/surefire-2.12.4.pom (14 kB at 34 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.jar (30 kB at 70 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.4/maven-jar-plugin-2.4.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.4/maven-jar-plugin-2.4.pom (5.8 kB at 14 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom (13 kB at 32 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/21/maven-parent-21.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/21/maven-parent-21.pom (26 kB at 61 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/apache/10/apache-10.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/apache/10/apache-10.pom (15 kB at 35 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.4/maven-jar-plugin-2.4.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.4/maven-jar-plugin-2.4.jar (34 kB at 83 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/3.2.1/maven-shade-plugin-3.2.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/3.2.1/maven-shade-plugin-3.2.1.pom (9.3 kB at 23 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/3.2.1/maven-shade-plugin-3.2.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/3.2.1/maven-shade-plugin-3.2.1.jar (114 kB at 240 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom (6.4 kB at 16 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.jar (27 kB at 67 kB/s)
Downloading from oss-snapshots-repo: https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-core/2.0-SNAPSHOT/maven-metadata.xml
Downloading from oss-snapshots-repo: https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-core/2.0-SNAPSHOT/pi4j-core-2.0-SNAPSHOT.pom
[WARNING] The POM for com.pi4j:pi4j-core:jar:2.0-SNAPSHOT is missing, no dependency information available
Downloading from oss-snapshots-repo: https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-plugin-pigpio/2.0-SNAPSHOT/maven-metadata.xml
Downloading from oss-snapshots-repo: https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-plugin-pigpio/2.0-SNAPSHOT/pi4j-plugin-pigpio-2.0-SNAPSHOT.pom
[WARNING] The POM for com.pi4j:pi4j-plugin-pigpio:jar:2.0-SNAPSHOT is missing, no dependency information available
Downloading from oss-snapshots-repo: https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-plugin-raspberrypi/2.0-SNAPSHOT/maven-metadata.xml
Downloading from oss-snapshots-repo: https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-plugin-raspberrypi/2.0-SNAPSHOT/pi4j-plugin-raspberrypi-2.0-SNAPSHOT.pom
[WARNING] The POM for com.pi4j:pi4j-plugin-raspberrypi:jar:2.0-SNAPSHOT is missing, no dependency information available
Downloading from oss-snapshots-repo: https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-core/2.0-SNAPSHOT/pi4j-core-2.0-SNAPSHOT.jar
Downloading from oss-snapshots-repo: https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-plugin-pigpio/2.0-SNAPSHOT/pi4j-plugin-pigpio-2.0-SNAPSHOT.jar
Downloading from oss-snapshots-repo: https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-plugin-raspberrypi/2.0-SNAPSHOT/pi4j-plugin-raspberrypi-2.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.701 s
[INFO] Finished at: 2021-10-01T19:10:16+10:00
[INFO] ------------------------------------------------------------------------
**[ERROR] Failed to execute goal on project adafruit-oled-bonnet-toolkit: Could not resolve dependencies for project adafruit-oled-bonnet-toolkit:adafruit-oled-bonnet-toolkit:jar:0.0.2: The following artifacts could not be resolved: com.pi4j:pi4j-core:jar:2.0-SNAPSHOT, com.pi4j:pi4j-plugin-pigpio:jar:2.0-SNAPSHOT, com.pi4j:pi4j-plugin-raspberrypi:jar:2.0-SNAPSHOT: Could not find artifact com.pi4j:pi4j-core:jar:2.0-SNAPSHOT in oss-snapshots-repo (https://oss.sonatype.org/content/groups/public) -> [Help 1]**
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by lukehutch** [comment]
Hi, now that Pi4j-v2 has been released, you can remove the "`-SNAPSHOT`" version number suffix from the versions in the `pom.xml` file. I just checked this fix into git too, so `git pull` should make this change.

It's possible that the Pi4J-v2 API changed a bit between the beta version that I was depending on before, until the current version. Please report any additional problems that you discover.

Please let me know if this fixes the issue, and if so I'll close this bug.

**Comment by lukehutch** [comment]
Oops, I meant to leave the bug open :-)

**Comment by TheNopePlant** [comment]
Can confirm that removing -SNAPSHOT from the pom.xml file has resolved this issue.
