### ISSUE TITLE
Drawing individual pixels

### ISSUE THREAD

**Issue by DevLARLEY** [lukehutch/Adafruit-OLED-Bonnet-Toolkit#3]
Hi,
how would i be able to display individual pixels on the screen? I looked at the code and wasn't able to find any implementations.
Help would be much appreciated!

**Comment by lukehutch** [comment]
There's a Display.setPixel method, you can see it here:

https://github.com/lukehutch/Adafruit-OLED-Bonnet-Toolkit/blob/master/src/main/java/aobtk/font/FontChar.java#L186

**Comment by DevLARLEY** [comment]
Thanks for the quick response! Do I need to call the repaint method after that to apply the pixel to the screen?

**Comment by lukehutch** [comment]
@DevLARLEY Yes you do, sorry, I came back to this issue to tell you that, but you already figured it out :-)

Now that I look back at the code though (I wrote this a long time ago), I see that it's a bit more complicated than I remembered.

The `Display` class just manages a `byte[] pixBuffer`, with one byte per pixel, for rendering simplicity (it doesn't touch the hardware). That byte array is initially allocated, before drawing, and then packed into a bit buffer with one bit per pixel, after drawing but before sending the bits to the screen, using the following methods:

https://github.com/lukehutch/Adafruit-OLED-Bonnet-Toolkit/blob/master/src/main/java/aobtk/oled/Display.java#L51

https://github.com/lukehutch/Adafruit-OLED-Bonnet-Toolkit/blob/master/src/main/java/aobtk/oled/Display.java#L109

To actually write the bits to the screen, you need to use `OLEDDriver.update`:

https://github.com/lukehutch/Adafruit-OLED-Bonnet-Toolkit/blob/master/src/main/java/aobtk/hw/Bonnet.java#L180

If you use the `Bonnet` class, you can avoid the low-level stuff. Just allocate your own `Display`, then set pixels as you want, then call `Bonnet.scheduleDraw` to draw the `Dispay` to the `OLEDDriver`:

https://github.com/lukehutch/Adafruit-OLED-Bonnet-Toolkit/blob/master/src/main/java/aobtk/hw/Bonnet.java#L191

**Comment by lukehutch** [comment]
I'll close this since I think that's all the info you need, but feel free to ask followup questions if you do need more pointers.

Also, the code hasn't been updated in a while, especially the Pi4J dependency, so if you feel like submitting patches, feel free :-)
